### ISSUE TITLE
deleteOneRelationship: Error: Cannot read property 'zone' of undefined

### ISSUE THREAD

**Issue by jack-y** [jack-y/seneca-entity-crud#8]
Running the `check` command, it fires an error:

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'zone' of undefined
    at /mymicroservice/node_modules/seneca-entity-crud/entity-crud.js:503:39
    at deleteOneRelationship (/mymicroservice/node_modules/seneca-entity-crud/entity-crud.js:501:12)
    at /mymicroservice/node_modules/seneca-entity-crud/entity-crud.js:287:23
    at Array.forEach (native)
    at Seneca.deleteRelationships (/mymicroservice/node_modules/seneca-entity-crud/entity-crud.js:286:26)
```

To investigate: in the deleteOneRelationship function, find what variable can be null.
(maybe a relationship not read?)

**Comment by jack-y** [comment]
This was due to a malformed triggers configuration, not a bug.
